feat: switch account
Elytro-eth/Elytro pull request #15
Opened 2024-12-02 09:02 UTC by zhangzewei

2024-12-02 10:06 UTC, walkjoy requested changes

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/components/TokenList.tsx
> +        const price = item.price > 0 ? Number(balance) / Number(item.price) : 0;
const price = item.price > 0 ? Number(balance) / item.price : 0 ，如果 item.price>0 能通过，就说明 price 一定是 number 类型的。

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/constants/events.ts
> +  NETWORK: {
目前看来，没必要使用 eventbus

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/entries/side-panel/components/AccountsModal.tsx
> +  const [networkId, setNetworkId] = useState<string>('');
networkId 应该是从 currentAccount 取的

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/entries/side-panel/components/AccountsModal.tsx
> +                {chains.find((chain) => chain.id === account.networkId)?.name ||
同上

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/entries/side-panel/components/AccountsModal.tsx
> +    await wallet.switchNetwork(networkId.toString());
这里应该是切换账号，而不是切换网络。wallet 里面处理切换账号和切换网络的关系。

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/entries/side-panel/components/BasicAccountInfo.tsx
> +  const currentAccount = accounts
same

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/entries/side-panel/contexts/account-context.tsx
> +    RuntimeMessage.onMessage(EVENT_TYPES.NETWORK.ITEMS_UPDATED, updateChains);
不需要这样做

2024-12-02 10:06 UTC, walkjoy commented on apps/extension/src/entries/side-panel/contexts/account-context.tsx
> +    RuntimeMessage.onMessage(EVENT_TYPES.ACCOUNT.ITEMS_UPDATED, getAccounts);
same

2024-12-03 02:43 UTC, walkjoy commented on apps/extension/src/background/services/accountManager.ts
> +
also, isInitialized 没有用到？

2024-12-03 08:50 UTC, zhangzewei commented on apps/extension/src/background/services/accountManager.ts
> +      eventBus.emit(EVENT_TYPES.ACCOUNT.ITEMS_UPDATED);
这里我更新sdk放在了 wallet Controller 的SwitchNetwork里面

2024-12-03 08:55 UTC, zhangzewei commented on apps/extension/src/background/services/sdk.ts
>    }
ok

2024-12-03 08:56 UTC, zhangzewei commented on apps/extension/src/background/services/walletClient.ts
> +    this.init(this._chain.id);
这部分的话我先直接写在create那部分代码里面 后续如果有select Network的步骤之后再修改

2024-12-03 09:00 UTC, zhangzewei commented on apps/extension/src/entries/side-panel/contexts/account-context.tsx
> +    RuntimeMessage.onMessage(EVENT_TYPES.ACCOUNT.ITEMS_UPDATED, getAccounts);
removed

2024-12-03 09:01 UTC, zhangzewei commented on apps/extension/src/entries/side-panel/contexts/account-context.tsx
> +    RuntimeMessage.onMessage(EVENT_TYPES.NETWORK.ITEMS_UPDATED, updateChains);
removed

2024-12-03 09:13 UTC, zhangzewei commented on apps/extension/src/entries/side-panel/components/AccountsModal.tsx
> +  const [networkId, setNetworkId] = useState<string>('');
这个是创建新的Network上的Account的时候输入的

2024-12-03 09:13 UTC, zhangzewei commented on apps/extension/src/entries/side-panel/components/AccountsModal.tsx
> +    await wallet.switchNetwork(networkId.toString());
refactored

2024-12-08 13:49 UTC, merged